### ISSUE TITLE
CORS-Anywhereが遅い

### ISSUE THREAD

**Issue by fujie** [ctc-selmid/wallet#12]
cors-anywhereのサンプル実装（heroku）をそのまま使っているのでボトルネックとなっている

**Comment by fujie** [comment]
とりあえず自前のheroku（Hobby Dynos）にcors-anywhereをデプロイしてあるが、Azure Web Appへ統合したい

**Comment by fujie** [comment]
Issuer側でCORSを許可する形で実装済み（vcissuer/iboissuerのみ対応済み）
とりあえず以下の形でコメントアウト下のみなので、残件としては「appendCorsAnywhereをコールしている箇所を修正する」
export const appendCorsAnywhere = (os, url) => {
  return os === "web" ? `${url}` : url;
  //  return os === "web" ? `https://calm-brook-96834.herokuapp.com/${url}` : url;
};

**Comment by ookimaki** [comment]
### 背景
- もともとMSが提供しているIssuer, Verifier(QRコードを表示する部分)はCORSを許可していなかったので、ブラウザからアクセスする際にCORSが許可されていないというエラーが出ていた
- モバイルはCORSが関係ないので、ブラウザ版のみ発生する
- 最初はChromeのCORS用のエクステンションで対応してたけど一般公開する際に、誰でもCORSの制約を突破できるようにCORS Anywhereのサンプル版（super poor performance）を経由することにしていた
- 結局IssuerとかVerifierのQRコード側でCORSを許可すれば対応できるので、fujieさんが対応してくれた
- ので余計なコードを削除する

(ただこの対応をするとMSのCredential NinjaのIssue/Verifyがそのままでは動かなくなる可能性はある)

### 対応内容の検討

- appendCorsAnywhereの関数を削除
- appendCorsAnywhereを使っているところを使わないように実装
- コメントアウトされている部分を削除

CORSの問題は
