### ISSUE TITLE
OIDCの認可要求にstateをつける

### ISSUE THREAD

**Issue by fujie** [ctc-selmid/wallet#7]
CSRF対策、code置き換え対策としてOIDCの認可要求にstateをつけ、code受け取り時に検証を行う

**Comment by ookimaki** [comment]
### 概要
- Azure AD B2CにサインインするときにStateをパラメータで渡しつつ、そのParameterを検証できるようにする
- Stateの保持とかがアプリ側で必要になりそうかがまだあまりわかっていない
- Azure AD B2Cとの連携の部分が少し難しいかもしれない

**Comment by ookimaki** [comment]
一旦アクティビティ的な感じで内容を共有した

**Comment by ookimaki** [comment]
1. Azure AD B2Cにstateのパラメーターを投げてリダイレクトするようにする
2. Azure AD B2CからリダイレクトされるURLにstateがあることを確認する
3. AzureADB2Cへのリダイレクト時にstateをローカルに保持し、AzureADB2Cからリダイレクトされたときに一致するか検証する

注意点としては、stateはランダムにすること
